---
# This playbook demonstrates how to add a host dynamically to the inventory
# and then run a task on that host.
# It uses the `ansible.builtin.add_host` module to add a new host with
# specific parameters like `ansible_host`, `ansible_user`, and `ansible_password`.
- name: Install Apps locally on macOS using Homebrew
  hosts: localhost
  become: false
  gather_facts: yes
  tasks:    
    - name: Ensuring Homebrew Is Installed
      stat:
          path: /usr/local/bin/brew
      register: homebrew_check
      when: ansible_facts['os_family'] == "Darwin"
    
    - name: Debug Homebrew Check
      debug:
        msg: "Homebrew is installed"
      when: homebrew_check.stat.exists

    - name: Install Asciidoctor
      homebrew: 
        name: asciidoctor
        state: present