---
- name: Openshift network manageiq_policies
  hosts: localhost
  gather_facts: false
  
  # This playbook creates network policies for manageiq in an OpenShift cluster.
  # It ensures that only pods with the label 'app: manageiq' can communicate with
  # each other over TCP port 443, both for ingress and egress traffic.
  # The policies are applied to the 'manageiq' namespace.
  collections:
    - community.kubernetes

  tasks:
    - name: Create network policies for manageiq
      k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: manageiq-network-policy
            namespace: manageiq
          spec:
            podSelector:
              matchLabels:
                app: manageiq
            policyTypes:
              - Ingress
              - Egress
            ingress:
              - from:
                  - podSelector:
                      matchLabels:
                        app: manageiq
                ports:
                  - protocol: TCP
                    port: 443
            egress:
              - to:
                  - podSelector:
                      matchLabels:
                        app: manageiq
                ports:
                  - protocol: TCP
                    port: 443

  