- name: Install Apps locally on macOS using Homebrew
  hosts: localhost
  become: false
  gather_facts: yes
  tasks:    
    - name: Ensuring Homebrew Is Installed
      stat:
          path: /usr/local/bin/brew
      register: homebrew_check
      when: ansible_facts['os_family'] == "Darwin"
    
    - name: Debug Homebrew Check
      debug:
        msg: "Homebrew is installed"
      when: homebrew_check.stat.exists

    - name: Install Asciidoctor
      homebrew: 
        name: asciidoctor
        state: present