---
- name: Retrive user credentials from LDAP
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Retrieve user credentials from LDAP
      ldap_search:
        server_uri: "ldap://your-ldap-server"
        bind_dn: "cn=admin,dc=example,dc=com"
        bind_password: "admin_password"
        search_base: "ou=users,dc=example,dc=com"
        search_filter: "(uid={{ lookup('env', 'USER') }})"
        attributes:
          - uid
          - cn
          - mail
      register: ldap_result

    - name: Display retrieved user credentials
      debug:
        var: ldap_result.entries[0]
      when: ldap_result.entries | length > 0
      failed_when: ldap_result.entries | length == 0
   
    - name: Display error message if no user found
      debug:
        msg: "No user found with the specified criteria."
      when: ldap_result.entries | length == 0
      failed_when: ldap_result.entries | length == 0
   
    - name: Display LDAP search result
      debug:
        var: ldap_result
      when: ldap_result.entries | length > 0
      failed_when: ldap_result.entries | length == 0